title: "My DevOps Lab 1"
description: "A lab project for setting up Jenkins and Tomcat on AWS EC2"
logo: "" # Add path to logo file here if you have one, e.g. /assets/img/logo.png
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
